title: my github pages
author: nsudb
email: nsudb@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  looking for my website page
theme: minima
# social links
twitter_username: nil # DO NOT include the @ character, or else the build will fail!
github_username:  nsudb # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
